library('ggplot2')
pa <- as.data.frame(read.csv("tiemposno.csv"))
sec <-as.data.frame(read.csv("tiempos.csv"))
ambos<- data.frame()
ambos<-rbind(pa,sec)
ambos$Poblacion <- as.factor(ambos$Poblacion)
png(paste("ambos.png", sep=""), width=700, height=700)
ggplot(data=ambos,aes(x=Poblacion,y=Tiempo,fill=Tipo))+geom_boxplot()+ylab("Tiempos (s)")#stat_summary(fun.y=mean,geom="smooth",aes(group=Tipo,col=Tipo))
#boxplot(pa$Tiempos~pa$k, color="red")
graphics.off()